apiVersion: v1
kind: Service
metadata:
  name: ray-tracing-app-service
  labels:
    app: ray-tracing-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: ray-tracing-app